brew "chruby"
brew "git"
brew "macvim"
brew "node"
brew "postgresql"
brew "ruby-install"
brew "sqlite"
brew "the_silver_searcher"

tap "heroku/brew"
brew "heroku"

tap "homebrew/cask"
cask_args appdir: "/Applications"

cask "1password"
cask "appcleaner"
cask "iterm2"
cask "keepingyouawake"
cask "macdown"